### ISSUE TITLE
Remove tooltip lag

### ISSUE THREAD

**Issue by jschroeter** [Seitenbau/SBideo#17]
Is there some way to remove this timeout, at least when showing the tooltip?
 The lag is annoying :-)
https://github.com/Seitenbau/SBideo/blob/1a960dc46de2be7675dec1ca690502985679344b/src/components/videoLink/index.js#L22

**Comment by hamsterbacke23** [comment]
hmm 🤔 I think there should be a way 😂

**Comment by hamsterbacke23** [comment]
It‘s only there for not accidently closing the tooltip when moving the mouse from the link to the tooltippopup itself... the timer has to be limited to that usecase

**Comment by hamsterbacke23** [comment]
Partly fixed with a20eeea265c5a8605e49b071d959245a92155ad3 but now opened tooltips overlap for a short period of time .. closing all other tooltips when a new one opens might have to be solved by managing the children state in a parent component, I'm not sure right now how to do that elegantly

**Comment by jschroeter** [comment]
fixed in #18
