### ISSUE TITLE
Tooltip position outside browser window

### ISSUE THREAD

**Issue by jschroeter** [Seitenbau/SBideo#2]
Sometimes the tooltips are shown outside the window so not everything is visible

**Comment by kern-sb** [comment]
Hi Jakob, 

in letzter Zeit kriege ich immer wieder mal Benachrichtigungen über irgendwelche Github-Commits, mit denen ich gar nichts zu tun habe, könnt ihr da bitte mal nachschauen, warum ich da immer als Bobachter gesetzt werde? 

Danke, 
Tino
