### ISSUE TITLE
Demo of the app, e.g. on github

### ISSUE THREAD

**Issue by hamsterbacke23** [Seitenbau/SBideo#21]
It would be nice to have demo online to try the app on github directly

**Comment by jschroeter** [comment]
https://seitenbau.github.io/SBideo/

**Comment by jschroeter** [comment]
Please add this to readme and close the issue.

**Comment by hamsterbacke23** [comment]
Demo link added to README with  a2020c0ba001c7d40fbacf568e26f552c760e12c
